framework:
    router:
        resource: "%kernel.root_dir%/config/admin/routing.yml"
        strict_requirements: ~

easy_admin:
    site_name: 'Royaumes eternels [admin]'
    design:
        brand_color: '#8b0000'
    entities:
        Category:
            class: AppBundle\Entity\Category
        User:
            class: AppBundle\Entity\User
        Version:
            class: AppBundle\Entity\Version
        Article:
            class: AppBundle\Entity\Article