framework:
    router:
        resource: "%kernel.root_dir%/config/admin/routing.yml"
        strict_requirements: ~

easy_admin:
    site_name: 'Royaumes eternels [admin]'
    design:
        brand_color: '#8b0000'
    entities:
        Category:
            class: AppBundle\Entity\Category
        User:
            class: AppBundle\Entity\User
        Version:
            class: AppBundle\Entity\Version
        Quickie:
            class: AppBundle\Entity\Quickie
        Article:
            class: AppBundle\Entity\Article
            list:
                fields:
                    - 'published'
                    - 'publishedAt'
                    - 'titre'
                    - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }
                    - 'masterCategory'
                    - 'author'
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }
                    - 'categoryList'
                    - 'masterCategory'
                    - 'titre'
                    - 'slug'
                    - 'content'
                    - 'updatedAt'
                    - 'published'
                    - 'publishedAt'
                    - 'version'
                    - 'author'
            form:
                fields:
                    - 'titre'
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'content', type: 'ckeditor' }
                    - 'version'
                    - 'masterCategory'
                    - 'categoryList'
                    - 'author'
                    - 'published'
        Comment:
            class: AppBundle\Entity\Comment
        Slide:
            class: AppBundle\Entity\Slide
            list:
                fields:
                    - 'published'
                    - 'url'
                    - { property: 'image', type: 'image', base_path: '%app.path.slide_images%' }
            show:
                fields:
                    - 'published'
                    - 'url'
                    - 'content'
                    - { property: 'image', type: 'image', base_path: '%app.path.slide_images%' }
            form:
                fields:
                    - 'url'
                    - { property: 'imageFile', type: 'vich_image' }
                    - 'content'
                    - 'published'


bm_backup_manager:
    database:
        production:
            type: mysql
            host: "%database_host%"
            port: "%database_port%"
            user: "%database_user%"
            pass: "%database_password%"
            database: "%database_name%"
    storage:
        local:
             type: Local
             root: "%kernel.root_dir%/var/backup/"
        dropbox:
            type: Dropbox
            token: "%dropbox_token%"
            key: "%dropbox_key%"
            secret: "%dropbox_secret%"
            app: "%dropbox_app%"
            root: "%dropbox_root%"