<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;
use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{

    public function getByCategory(Category $category){
        return $this->createQueryBuilder('art')
            ->andWhere('art.published = 1')
            ->andWhere('art.masterCategory = :cat')
            ->leftJoin('art.categoryList','cat')
            ->orWhere('cat = :cat')
            ->setParameter('cat', $category)
            ->orderBy('art.publishedAt', 'desc')
            ->getQuery()
            ->execute();
    }

}
