<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;
use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{

    /**
     * @param Category $category
     * @param int $paginationSize
     * @param int $page
     * @return mixed
     */
    public function getByCategory(Category $category, $paginationSize, $page)
    {
        return $this->createQueryBuilder('art')
            ->andWhere('art.published = 1')
            ->andWhere('art.masterCategory = :cat')
            ->leftJoin('art.categoryList', 'cat')
            ->orWhere('cat = :cat')
            ->setParameter('cat', $category)
            ->orderBy('art.publishedAt', 'desc')
            ->setMaxResults($paginationSize)
            ->setFirstResult(($page - 1) * $paginationSize)
            ->getQuery()
            ->execute();
    }

    /**
     * @param Category $category
     * @return mixed
     */
    public function getCountByCategory(Category $category)
    {
        return $this->createQueryBuilder('art')
            ->select('COUNT(art)')
            ->andWhere('art.published = 1')
            ->andWhere('art.masterCategory = :cat')
            ->leftJoin('art.categoryList', 'cat')
            ->orWhere('cat = :cat')
            ->setParameter('cat', $category)
            ->orderBy('art.publishedAt', 'desc')
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @param int $paginationSize
     * @param int $page
     * @return mixed
     */
    public function getAll($paginationSize, $page)
    {
        return $this->createQueryBuilder('art')
            ->andWhere('art.published = 1')
            ->orderBy('art.publishedAt', 'desc')
            ->setMaxResults($paginationSize)
            ->setFirstResult(($page - 1) * $paginationSize)
            ->getQuery()
            ->execute();
    }

    /**
     * @return mixed
     */
    public function getAllCount()
    {
        return $this->createQueryBuilder('art')
            ->select('COUNT(art)')
            ->andWhere('art.published = 1')
            ->orderBy('art.publishedAt', 'desc')
            ->getQuery()
            ->getSingleScalarResult();
    }

}
