<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * @return mixed
     */
    public function getCategoryWithArticle()
    {
        return $this->createQueryBuilder('cat')
            ->leftJoin('cat.articleList', 'art')
            ->orWhere('art.published = 1')
            ->leftJoin('cat.masterArticleList', 'artMaster')
            ->orWhere('art.published = 1')
            ->orWhere('artMaster.published = 1')
            ->orderBy('cat.name', 'asc')
            ->getQuery()
            ->execute();
    }

}
