<?php

namespace AppBundle\Repository;

/**
 * QuickieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuickieRepository extends \Doctrine\ORM\EntityRepository
{
}
