fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

front:
    resource: "@AppBundle/Controller/Front"
    type:     annotation

writer:
    resource: "@AppBundle/Controller/Writer"
    type:     annotation

admin:
    resource: "@AppBundle/Controller/Admin"
    type:     annotation