version: '2'
services:
    nginx:
        build: nginx-preprod
        ports:
            - ${NGINX_UNSECURE_PORT}:80
            - ${NGINX_SECURE_PORT}:443
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
          - ${PHPMYADMIN_PORT}:80
    mailcatcher:
        image: yappabe/mailcatcher
        ports:
          - ${MAILCATCHER_PORT}:1080