version: '2'
services:
    nginx:
        build: nginx-preprod
        ports:
            - ${NGINX_UNSECURE_PORT}:80
            - ${NGINX_SECURE_PORT}:443
            - ${MAILCATCHER_PORT}:1080
            - ${PHPMYADMIN_PORT}:82
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
    mailcatcher:
        image: yappabe/mailcatcher
    compass:
        image: antonienko/compass-watch
        command: watch --poll /src/compass
        volumes:
            - ../app/Resources/style/:/src
            - ../web/:/src/public