version: '3.7'
services:
    nginx:
        build: nginx
        ports:
            - ${NGINX_UNSECURE_PORT}:80
            - ${NGINX_SECURE_PORT}:443
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/nginx/:/var/log/nginx
            - /etc/letsencrypt:/etc/letsencrypt
            - /data/letsencrypt:/data/letsencrypt
        deploy:
          restart_policy:
            condition: always