version: '2'
services:
    nginx:
        build: nginx
        ports:
            - ${NGINX_UNSECURE_PORT}:80
            - ${NGINX_SECURE_PORT}:443
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx