imports:
    - { resource: ../config_dev.yml }
    - { resource: config.yml }


framework:
    router:
        resource: "%kernel.root_dir%/config/app/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }