framework:
    router:
        resource: "%kernel.root_dir%/config/writer/routing.yml"
        strict_requirements: ~

easy_admin:
    site_name: 'Royaumes eternels [writer]'
    design:
        brand_color: '#008b00'
    entities:
        Category:
            class: AppBundle\Entity\Category
        Version:
            class: AppBundle\Entity\Version
        Article:
            class: AppBundle\Entity\Article
            list:
                fields:
                    - 'published'
                    - 'publishedAt'
                    - 'titre'
                    - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }
                    - 'masterCategory'
                    - 'author'
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }
                    - 'categoryList'
                    - 'masterCategory'
                    - 'titre'
                    - 'slug'
                    - 'content'
                    - 'updatedAt'
                    - 'published'
                    - 'publishedAt'
                    - 'version'
                    - 'author'
            form:
                fields:
                    - 'titre'
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'content', type: 'ckeditor' }
                    - 'version'
                    - 'masterCategory'
                    - 'categoryList'
                    - 'author'
                    - 'published'