framework:
    router:
        resource: "%kernel.root_dir%/config/writer/routing.yml"
        strict_requirements: ~

easy_admin:
    site_name: 'Royaumes eternels [writer]'
    design:
        brand_color: '#008b00'
    entities:
        Category:
            class: AppBundle\Entity\Category
        Version:
            class: AppBundle\Entity\Version
        Article:
            class: AppBundle\Entity\Article